if fs.exists("disk/startup.lua") then
    fs.delete("disk/startup.lua")
    fs.delete("disk/json.lua")
    fs.delete("disk/GUI.lua")
    fs.delete("disk/tracer.lua")
    fs.delete("startup.lua")
    fs.delete("data.txt")
    fs.delete("json.lua")
    fs.delete("GUI.lua")
    fs.delete("tracer.lua")
else
    wfile = fs.open("disk/data.txt","wb")
    print("What is the WebSocket URL?")
    wfile.write(io.stdin:read() .. "\n")
    print("What is my x coordinate?")
    wfile.write(io.stdin:read() .. "\n")
    print("What is my y coordinate?")
    wfile.write(io.stdin:read() .. "\n")
    print("What is my z coordinate?")
    wfile.write(io.stdin:read() .. "\n")
    print("Which direction am I facing?")
    wfile.write(io.stdin:read() .. "\n")
    print("What is the server IP?")
    wfile.write(io.stdin:read() .. "\n")
    print("What is my owner's ID?")
    wfile.write(io.stdin:read() .. "\n")
    wfile.write("{{\"\",0},{\"\",0}}")
    wfile.close()
end
shell.run("wget", "https://raw.githubusercontent.com/Gopi200/Turtlejs/dev/Turtlefiles/json.lua", "/disk/json.lua")
shell.run("wget", "https://raw.githubusercontent.com/Gopi200/Turtlejs/dev/Turtlefiles/startup.lua", "/disk/startup.lua")
shell.run("wget", "https://raw.githubusercontent.com/Gopi200/Turtlejs/dev/Turtlefiles/GUI.lua", "/disk/GUI.lua")
shell.run("wget", "https://raw.githubusercontent.com/Gopi200/Turtlejs/dev/Turtlefiles/tracer.lua", "/disk/tracer.lua")
os.reboot()